quiz_base_headers = [
    "name",
    "id",
    "sis_id",
    "root_account",
    "section",
    "section_id",
    "section_sis_id",
    "submitted",
]
uwrs_headers_4q = [
    *quiz_base_headers,
    "question1",
    "1.0",
    "question2",
    "2.0",
    "question3",
    "3.0",
    "question4",
    "4.0",
    "n correct",
    "n incorrect",
    "score",
]
uwrs_headers_5q = [
    *quiz_base_headers,
    "question1",
    "1.0",
    "question2",
    "2.0",
    "question3",
    "3.0",
    "question4",
    "4.0",
    "question5",
    "5.0",
    "n correct",
    "n incorrect",
    "score",
]
uwrs_headers_6q = [
    "name",
    "id",
    "sis_id",
    "root_account",
    "section",
    "section_id",
    "section_sis_id",
    "submitted",
    "disclaimer",
    "0.0",
    "question1",
    "1.0",
    "question2",
    "2.0",
    "question3",
    "3.0",
    "question4",
    "4.0",
    "question5",
    "5.0",
    "n correct",
    "n incorrect",
    "score",
]
uwrs_drop_headers_4q = [
    "root_account",
    "1.0",
    "2.0",
    "3.0",
    "4.0",
    "n correct",
    "n incorrect",
    "score",
]
uwrs_drop_headers_5q = [
    "root_account",
    "1.0",
    "2.0",
    "3.0",
    "4.0",
    "question5",
    "5.0",
    "n correct",
    "n incorrect",
    "score",
]
uwrs_drop_headers_6q = [
    "root_account",
    "disclaimer",
    "0.0",
    "1.0",
    "2.0",
    "3.0",
    "4.0",
    "question5",
    "5.0",
    "n correct",
    "n incorrect",
    "score",
]
ipaq_headers_8q = [
    *quiz_base_headers,
    "acknowledgement",
    "0.0",
    "question1",
    "1.0",
    "question2",
    "2.0",
    "question3",
    "3.0",
    "question4",
    "4.0",
    "question5",
    "5.0",
    "question6",
    "6.0",
    "question7",
    "7.0",
    "n correct",
    "n incorrect",
    "score",
]
ipaq_drop_headers_8q = [
    "root_account",
    "0.0",
    "1.0",
    "2.0",
    "3.0",
    "4.0",
    "5.0",
    "6.0",
    "7.0",
    "n correct",
    "n incorrect",
    "score",
]
ipaq_headers_7q = [
    *quiz_base_headers,
    "question1",
    "1.0",
    "question2",
    "2.0",
    "question3",
    "3.0",
    "question4",
    "4.0",
    "question5",
    "5.0",
    "question6",
    "6.0",
    "question7",
    "7.0",
    "n correct",
    "n incorrect",
    "score",
]
ipaq_drop_headers_7q = [
    "root_account",
    "1.0",
    "2.0",
    "3.0",
    "4.0",
    "5.0",
    "6.0",
    "7.0",
    "n correct",
    "n incorrect",
    "score",
]
